### ISSUE TITLE
Problem activiting

### ISSUE THREAD

**Issue by gregfielding** [slaFFik/SeoPress#1]
Warning: require_once(admin/getpro_tab.php) [function.require-once]: failed to open stream: No such file or directory in /home/housings/public_html/wp-content/plugins/Themekraft-SeoPress-Free-ab9d927/seopress.php on line 76

I have a multisite community, but was just activating on the main blog.

**Comment by mahype** [comment]
Thank you for reporting! I will see and fix this bug.

**Comment by mahype** [comment]
Bug is fixed on the actual git version.
