### ISSUE TITLE
Call to undefined function auth_redirect() 

### ISSUE THREAD

**Issue by mahype** [slaFFik/SeoPress#18]
With “WP_DEBUG

Fatal error: Call to undefined function auth_redirect() in /****/httpdocs/wp-admin/admin.php on line 66

**Comment by gregfielding** [comment]
mahype

I think you've seen this elsewhere, but this error appears for me when trying to add a widget to a sidebar.

**Comment by mahype** [comment]
OK! Thanks for this advice! ;)
