### ISSUE TITLE
Plugins Page Not Complete

### ISSUE THREAD

**Issue by gregfielding** [slaFFik/SeoPress#2]
I'm getting this message...

Please config your "Map" plugin before you setup your component meta! (Do this at the bottom of this page)

But there is nothing at the bottom of the page. For what it's worth, I think this is for my Mapology plugin...

**Comment by mahype** [comment]
Can you see the "Configurate Plugins" section?

**Comment by gregfielding** [comment]
Yes, it does...guess I didn't realize that's what it was. 

But, it's not saving my checkmarks. I checked that "maps" has a directory page, hit save settings, and nothing happens - and the box still shows as unchecked.

**Comment by mahype** [comment]
OK I will check the issue and I'll think about to put the configutation into th yellow area. Your not the first who said that.

**Comment by mahype** [comment]
I have moved the configuration area to the plugins. I think this will be more instinctive. The checkmarks problem is solved. Happy testing ;) Tomorrow I will go further.
