### ISSUE TITLE
an error in seopress 

### ISSUE THREAD

**Issue by drhoussem** [slaFFik/SeoPress#26]
When i set Group Forum title as: %%component_name%% forum | %%site_name%%
it didn't show the group name 'groups forums | mysitename'
the same error is with: Group Members title !

**Comment by mahype** [comment]
Hello,

why did ou closed that issue?

Sven

**Comment by drhoussem** [comment]
The error was in my seopress plugin ! i updated the plugin but I haven't updated the titles !
