### ISSUE TITLE
Page types collapsed menus not working !

### ISSUE THREAD

**Issue by drhoussem** [slaFFik/SeoPress#27]
When I go to 'Page types' page I see that all collapsed menus are not working !

**Comment by drhoussem** [comment]
even wordpress collapsed menus are not working in this page :(

**Comment by mahype** [comment]
Hello,

do you have switched off the other plugins? We've got to test if its a conflict. 

Sven

**Comment by drhoussem** [comment]
No ! but I think that the conflit is with W3TC ! I'll try to switch it off tomorrow.

**Comment by mahype** [comment]
That could be! Thank you for your help! ;)

**Comment by drhoussem** [comment]
When I desable buddypress menus work fine !! O.o

**Comment by drhoussem** [comment]
I'm using buddypress 1.2.8 !

**Comment by drhoussem** [comment]
and also Special Tag autocomplete didn't work !

**Comment by mahype** [comment]
Can you send me login data for yor wordpress Admin and FTP to team [at] themekraft.com ? Otherwise it's not possible to check your errors. I woul'd check the errors and will fix the bug if its possible to do this in the plugin.

Thank you! ;)
