### ISSUE TITLE
Issue with french language

### ISSUE THREAD

**Issue by drhoussem** [slaFFik/SeoPress#28]
When I select: Activité | Sitename as activity page title it appear: ActivitÃ©

**Comment by mahype** [comment]
Hello,

thanks for sending this issue! I will look for the issue. By the way, can you send me your language file for the plugin? Would be nice to implement it and it would be easier to debug.

Thank you!

Sven

**Comment by drhoussem** [comment]
I'm not using a language file but i set this titles manually :(
