### ISSUE TITLE
%%userfullname%% doesn't work

### ISSUE THREAD

**Issue by gregfielding** [slaFFik/SeoPress#3]
%%userdisplayname%%,  %%usernicename%%, and %%userfullname%% all show the same results.

My name is Greg Fielding. My username is gregfielding. How do I show "Greg Fielding"?

http://housingstorm.com/gregfielding/

**Comment by mahype** [comment]
Maybe I have to delete %%userfullname%%. As you said, the special tags all returning the username. This is a historical issue. I've assumed special tags from the 1.0.6 version of SeoPress and there have to be the same problem. If you want to show your real name you have to use %%userdisplayname%% and (!) to setup you profile on your wp-admin or on Buddypress profile. You can change it in "wp-admin" at "Display name publicly as" and in Buddypress under your Profile. Maybe I only let %%username%% which automatically will switch to fullname if name is set.

Thank you for reporting! ;)

**Comment by mahype** [comment]
I have decided to delete all username special tags and to implement the new one %%username%%. I think for SEO optimizing it should be optimal and you don't need more. The new code is online ;)
