### ISSUE TITLE
Adding Single Activity (Permalink.php) SEO

### ISSUE THREAD

**Issue by gregfielding** [slaFFik/SeoPress#4]
I see the Activity directory, but is there any way to include SEO for individual activities?

**Comment by gregfielding** [comment]
Or maybe it's entry.php...?

**Comment by mahype** [comment]
Thanks! I will take a look and change it!

**Comment by mahype** [comment]
I have added the activity item to SeoPress. There will come some Special Tags for activities soon.

**Comment by gregfielding** [comment]
Great! Looking forward to it.
