### ISSUE TITLE
Saving error

### ISSUE THREAD

**Issue by mahype** [slaFFik/SeoPress#46]
nach Speichern einer Seite erhalte ich folgende Fehlermeldung:
Fatal error: Call to undefined function get_post_thumbnail_id() in /…/wp-content/plugins/seopress/facebook/loader.php on line 98

**Comment by amites** [comment]
Getting this error at the bottom of each page in the admin when opened for editing
seems to be an import error as the function is defined within /wp-includes/post-thumbnail-template.php

**Comment by amites** [comment]
Just submitted a pull request with a patch for this issue
