### ISSUE TITLE
Conflict between Profile Activity and Activity Index

### ISSUE THREAD

**Issue by gregfielding** [slaFFik/SeoPress#5]
Found another bug.

%%activity_author%% works for individual activities, see http://housingstorm.com/patrickbutterfield/activity/32067

%%username%% works for the Profile (full profile) section, see http://housingstorm.com/patrickbutterfield/profile/

But neither work for Profile/Activity, see http://housingstorm.com/patrickbutterfield/activity/

**Comment by mahype** [comment]
Hi Greg!

I have fixed the bug. After inserting the Activity page in SeoPress, the profile pages where not identyfied correct ;)

Additional I have changed the special tag %%username%% to %%user_name%%, to be more strict with the name structure of the special tags.

Thank you again! ;)

Sven
