### ISSUE TITLE
incorrect URL to this forum on WP official page

### ISSUE THREAD

**Issue by HongPong** [slaFFik/SeoPress#59]
Hi, i noticed that on
http://wordpress.org/extend/plugins/seopress/
there is a link to
https://github.com/Themekraft/SeoPress-Free/issues 
is not the correct URL to use.

should be 
https://github.com/Themekraft/SeoPress/issues

Regards!

**Comment by mahype** [comment]
Hi HongPong,

thank you for submitting! I have changed the URL right now.

Sven
