### ISSUE TITLE
buddypress forums fail to load.

### ISSUE THREAD

**Issue by jcircle** [slaFFik/SeoPress#62]
buddypress forums version 1.5.6. With both free and normal SEO press enabled the forums will not load on the page.
Something in buddypress change from 1.5.5 to 1.5.6?

Plug in enabled. the page stops at the header. plug in disable page loads.

**Comment by Cuffsmaster** [comment]
I wanted to add thoughts to this issue --  NO SEO I have tried works.   I think it is a bigger issue than just pressseo.  
It also was somewhat of a problem BEFORE this latest release of wordpress and buddypress but I did finally get wordpressSEO by Yoast to work.     Finally after I got it all working - ---  BOOM the upgrade to wordpress 3.4 and and new buddypress -  and it is the same issue as before.  
when you go to forum the pages will freeze.    Disable whatever SEO you are using and it works.  
There are some problems with it freezing with other programs but this is the major one.   It has cost me just time and energy and I am sick of this problem.  

I think it is a theme problem not a SEO problem.    The problem in a lesser form actually predates the updates.

**Comment by Cuffsmaster** [comment]
Additional information: 
oh it all works fine with the default buddypress theme -- I just can't stand the look and feel of it or I'd change today and forget about this huge headache for the last month or more.  Yes this problem has gone on before the new versions of wordpress or buddypress 

  However until you find the problem I may have to use the default buddyprsss theme.

**Comment by Cuffsmaster** [comment]
another hint --  

when you activate the plugin - "WP UI - Tabs, accordions and more" -  OR  "wp-Typograph"   you get the very same hangup - it looks the very same -  Everything works but forums and it hands up with only part of the header image showing.  
same reaction as trying to use any SEO 

All these problems were prior to the wordpress update.  

So to recap one or more of these plugins when activated causes the same reaction in forums 
1) any SEO including pressseo
2) WP - UI taps ,,,
3) wp-Typograph 

ALL cause wordpress forums to CRASH --  THis happened before the change but I thought I had it fixed to where I could use part of them but was never able to use WP- UI or Wp -typograph  
NOW I am back to where I started and think it is your problem to find the answer too.  I am frustrated beyon belief

**Comment by Cuffsmaster** [comment]
Prior to the new wordpress and buddypress updates 
I tried all sorts of combinations and nothing allowed me to have an SEO 
I deleted wordpress accept files and reloaded pages and post into new database - then reloaded wordpress 
I finely got it to work with the  Wordpress-seo plugin installed -  without causing the forum to freeze  
THEN came the new wordpress & buddypress version and I am BACK to square ONE
let me know if you want to get into my system.   Good luck

**Comment by svenl77** [comment]
@Cuffsmaster, we will find this issue now. I just started testing intensive. sorry for your discomfort 

It looks like there is something wrong with the menu and seo... Will let you know after I found the issue.

@mahype seopress tkf is not compatible with the new cc 2.0 version, could you update it  please

Fatal error: Cannot redeclare tk_is_signup() (previously declared in /Users/svenl77/Sites/cc-free/wp-content/themes/Custom-Community/core/includes/tkf/wp/detect.php:210) in /Users/svenl77/Sites/cc-free/wp-content/plugins/seopress/includes/lib/wordpress/wp.inc.php on line 13

**Comment by Cuffsmaster** [comment]
Thank you Sven for telling me.

In the mean time I will do as you suggested in the first email and try to figure out where the error starts and causes it to freeze.  If I figure that out I will fire off an email to you.

Jeff

**Comment by Cuffsmaster** [comment]
Sven, 

ok if you go to TEST menu -- (I changed if from your menu)  

If you remove the last menu idem - "setting goals for a slave"  the forums seems to work   

I didn't change it so you could examine it if you wish to see what's wrong.  

BUT,,,,,  interesting enough I removed the "setting goals for a slave" from the mainmenu and it STILL does not work.    Must be more than one issue.  

Jeff

**Comment by Cuffsmaster** [comment]
YET MORE INFORMATION

OK -  
I have found two pages that lock the forum with your theme but NOT the default buddypress one.  

1)  the sitemap page  
2) setting goals for a slave 

BOTH are at the BOTTOM of the TEST menu.    

FOR some reason that were not on the TEST menu you created yesterday 

BUT>>>  

even with removing both menus the mainmenu will not work .         

This is frustrating.  

I have NO idea why these pages don't work.    sitemap is a plugin but the other page is NOT.

**Comment by Cuffsmaster** [comment]
Sven

HERE is a LARGE list of pages that WORK with the DEFAULT Buddypress theme but CRASH the forum with your theme.   I have looked that them and don't know why they crash using your theme.  I am not changing them until you have a change to examine them to see if this is something you need to know.  

They are:  

sitemap 
setting goals 
slave preformance based on service

Hypnosis and what is hypnosis slave training?

THE B.D.S.M. lifestyle - an alternative intimacy

Pleasure of Pain

victorian Brothels and birching 

The fogging whore of old London"

stages of growth in bdsm

Trusting a master

slave training rules, modes & positions

slave modes

slave's cage

Rules, protocols and rituals of a slave in bdsm lifestyle. 

THE  access to my site is still the same   User: JCircle     Password:  pleasefix  

also I gave you the accept to my BlueHost account and it is still the same.  It's in a prior email to you  but if you need and can't find it you can email or yahoo messages me at Cuffsmaster

Please look at these pages and tell me WHY and what to do to fix  otherwide your theme can't be used.   

Thanks 

Jeff
