### ISSUE TITLE
SeoPress bugs with Group Forums

### ISSUE THREAD

**Issue by konradsroka** [slaFFik/SeoPress#66]
...reported by seopress user in buddypress.org forums: 

---

Not sure if ThemeKraft team is aware of this one.

I’m using:
WP 3.4.1
BuddyPress 1.6
Frisco Theme

I’ve just installed your SeoPress plugin and Group Forum topics got messed.
It allows to create new topics, shows them, but doesn’t allow to delete or even consider it as existing.

Once one topic is created and viewing it on its topic page, title doesn’t show and instead shows (0 Posts). When deleted, gives a not found page.

Deactivating the plugin everything gets normal.

Looking for the updated version of this wonderful plugin. 

---

link: http://buddypress.org/community/groups/how-to-and-troubleshooting/forum/topic/post-update-and-members-directory-not-working-after-upgrade-to-1-6/#post-135777

**Comment by slaFFik** [comment]
Confirm. Will fix.

**Comment by slaFFik** [comment]
Found the problem! Finally...
