### ISSUE TITLE
404 page support

### ISSUE THREAD

**Issue by henrywright** [slaFFik/SeoPress#69]
Although most site areas are taken care of by the plugin, I noticed that the 404 page isn't covered. Any plans to add support for setting the 404 page title, description and so on?

**Comment by slaFFik** [comment]
Hi,
Yes.
In general I'm desperately trying to find time to fix bugs and implement new features...

**Comment by henrywright** [comment]
Hi slaFFik

Great work on the plugin. Seems you guys have nailed BuddyPress page titles which many SEO plugin authors cannot seem to do
